### ISSUE TITLE
ModuleLoad missing

### ISSUE THREAD

**Issue by McSwaggens** [andreyorst/powerline.kak#10]
## Problem description

Installed *powerline.kak* using *plug-kak* and using the example configuration listed in the `README.md`.
I'm getting the following 2 error messages in the `*debug*` buffer:
```
.../modules/position.kak:13:848: 'hook' no such hook: 'ModuleLoad'                     
plug.kak: Error occured while loading andreyorst/powerline.kak plugin:                                                               

```
And yes... The last line is blank.
No powerline commands show up either.

## Environment information
Kakoune version: 09e1ec97a9d7925c9d4411f4f274919aeea1bf75
OS version: ArchLinux, kernel 5.1.11
`fish` executable version: 3.0.2-1080-g097d6c3c5

**Comment by andreyorst** [comment]
You need latest master build to use this plugin. It uses new module system introduced after the last stable release.

**Comment by McSwaggens** [comment]
That fixed the issue but then I got an the following issue:
```
plug.kak: Can't declare highlighters for kakrc.                                                                                                                       
          Detailed error: 2:6: 'add-highlighter' no such id: 'kakrc'                                                                                                  
plug.kak: Error occured while loading andreyorst/powerline.kak plugin:                                                                                                
          2:6: 'evaluate-commands' 26:2202: 'evaluate-commands' no such command: 'defer'
```
For anyone wondering, I fixed the above error by switching to the *dev* branch on plug.kak which supports the `defer` command and everything works perfectly now.
Thanks.

**Comment by Vintodrimmer** [comment]
I have built the latest master branch version, yet the problem persists.

Could it be due to ![this commit](https://github.com/mawww/kakoune/commit/eae92c9ae3a15464f336f3e70fce2c8c579ca955) or am I doing something wrong?

**Comment by andreyorst** [comment]
No, you're right, Kakoune recently changed this hook's name. I'll update my plugins asap
